import MainLayout from "@/components/MainLayout";
import "./globals.css";
import MenuContextProvider from "@/context/MenuContext";
import Cards from "@/components/Cards";

export const metadata = {
  title: "Games Global",
  description: "Generated by Nwabisa Madyibi Redwood-Sawyerr",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <MenuContextProvider>
          <MainLayout>{children}</MainLayout>
        </MenuContextProvider>
        
      </body>
    </html>
  );
}
